# Auto-generated by i18n/gen_strings.py
# Contains QT_TRANSLATE_NOOP entries so pyside6-lupdate can extract all UI/log text.
from PySide6.QtCore import QT_TRANSLATE_NOOP

STRINGS = [
    QT_TRANSLATE_NOOP('App', "Inconnu"),  # core/models.py
    QT_TRANSLATE_NOOP('App', "Chemin HLS explicite (.m3u8)."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Faible"),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Flux non chiffré (http)."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Flux servi depuis une IP brute (pas de domaine)."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Hébergement"),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Hébergement CDN connu ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Hôte manquant dans l'URL."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Libellé sensible ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Modéré"),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Mot-clé chemin ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Mot-clé hôte indicatif de restream ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Pays du flux cohérent avec l'identifiant de chaîne."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Port non standard ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Schéma non standard ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "TLD aligné sur pays courant ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "TLD fréquent sur flux non officiels ("),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "URL incomplète ou sans schéma."),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "Élevé"),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', "≠ pays annoncé"),  # core/risk_scoring.py
    QT_TRANSLATE_NOOP('App', ", programmes="),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Aucun --site trouvé pour tes tvg-id. (tvg-id pas couvert par iptv-org/epg)"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Aucun channel match dans"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Aucun site n'a produit de guide XML (tous SKIP/KO)."),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Aucun tvg-id fourni"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Fichier channels introuvable:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "IPTV_EPG_MAX_SITES"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Repo EPG invalide:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Sites SKIP:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Aucun site trouvé pour ces tvg-id."),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] IPTV_EPG_MAX_SITES<=0 -> pas de limite, tous les sites candidats seront tentés."),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Merge OK: channels="),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Non couverts (exemples):"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Note: sites ignorés:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] RUN:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] SKIP"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Sites candidats:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] Sites sélectionnés ("),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "[EPG] custom channels:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "npm grab a échoué (code="),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "npm grab terminé, mais XML manquant/vide:"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "npm grab timeout ("),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "npm_grab_site: il faut soit site, soit channels_path"),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "pour ces tvg-id (astuce: xmltv_id peut contenir @SD/@HD)."),  # epg_npm_bridge.py
    QT_TRANSLATE_NOOP('App', "Outils XMLTV: téléchargement d'un guide (XML/ZIP) puis parsing en flux pour insertion en DB."),  # epg_xmltv.py
    QT_TRANSLATE_NOOP('App', "# Contains QT_TRANSLATE_NOOP entries so pyside6-lupdate can extract all UI/log text."),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "Archives"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "Collected"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "QT_TRANSLATE_NOOP('App',"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "STRINGS = ["),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "TESTS"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "from PySide6.QtCore import QT_TRANSLATE_NOOP"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "strings ->"),  # i18n/gen_strings.py
    QT_TRANSLATE_NOOP('App', "### Grouped by broadcast area"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "### Grouped by category"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "### Grouped by language"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "#### Countries"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "#EXTINF:-1 tvg-id=\""),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "#EXTINF:-1 tvg-id=\"tf1.fr\",TF1"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "#EXTINF:-1,Movie 24/7"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "%Y-%m-%d %H:%M"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "(Aucun programme dans cette plage.)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "(Erreur EPG:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "(sans nom)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "(sans titre)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "); fallback PLAYLISTS.md KO ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', ", age"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', ", total"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "- ajuste les filtrees)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "--- CONTAINS ---"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "--- FIRST 40 LINES ---"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "ALL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "ALTER TABLE channels ADD COLUMN vlc_opts TEXT"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "ALTER TABLE playlists ADD COLUMN epg_url TEXT DEFAULT ''"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "API feeds ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "API iptv-org"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "API iptv-org/api KO ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "API streams ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Afficher"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Annuler"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "App"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Apparence"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Aucune URL détectée. Sélectionne une feuille (URL) ou un parent (Category/Language/Country)."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Aucune playlist chargee."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Auto EPG pour playlists Salon (cache 12h)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Avec referrer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Avec user-agent"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "CONTENT-TYPE:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Category"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaine"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaine precedente (playlist)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaine suivante (playlist)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaine:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaine: -"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Channel"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement du lecteur..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement feeds.json..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement playlists sélectionnées"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement streams.json + generation M3U..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chargement streams.json..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Charger dans le lecteur"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Charger dans le player"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Charger la sélection"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chaînes"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chemin EPG non configuré"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chemin OK:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Chemin absent:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Choisir le dossier EPG"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Choisir une playlist"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Choisis une playlist :"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Clear"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Colle l'URL .m3u/.m3u8 :"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Config: enregistrée ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Config: prévisualisation ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Configuration"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Contains category heading?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Contains language heading?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Country"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Counts:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "DEBUG"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "DELETE FROM channels WHERE playlist_id=?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "DELETE FROM epg_programs"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "DELETE FROM playlists WHERE id=?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Debut"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Debut test URLs..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Demo"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Description…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Dossier EPG (npm/XML)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Dossier repo introuvable:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Dossier sites introuvable:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Dupliquer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Début"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG (XMLTV)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG chargé en mémoire"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG/Node"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: (pas de tvg-id) → impossible d'ouvrir le guide."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: URL/dossier vide."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: analyse de la cible..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: aucune tvg-id"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: cache charge ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: cache invalide ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: couverture"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: erreur Exporte:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: erreur import:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: erreur:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: generation via repo npm:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: import OK."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: import termine."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: insertion snapshot ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: pas chargé."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: preparation..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: rien a exporter (pas de snapshot)."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: snapshot exporte ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: sélectionne une chaîne."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "EPG: telechargement + import:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "ERROR"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Editeur: playlist Salon chargee ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Emplacements"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Enregistrer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Enregistrer '"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Ensuite:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Ensuite: -"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Ensuite: —"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur API:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur fusion URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur telechargement"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Erreur: --site manquant. Utilise --find-tvg pour t'aider, ou choisis un site dans SITES.md."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Essaye un autre tvg-id (ex: CFUTDT.ca@SD, CIVMDT.ca@SD, etc.)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Exporte:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Exporter"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Exporter EPG (snapshot)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Exporter au Salon"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Exporter playlist filtree"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "FINAL URL:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feed"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feeds (API iptv-org)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feeds: chargement OK ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feeds: erreur API:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feeds: erreur import:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Feeds: import OK ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fichier TXT (liens m3u/m3u8)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fichier XML de sortie (relatif = dans le repo)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Filtre chaines (nom, groupe, tvg-id)..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Filtre playlist (nom, groupe, tvg-id)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fin"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "First category items:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "First language items:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Format"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion TXT liens"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion TXT: KO"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion TXT: aucun lien m3u/m3u8 detecte."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion TXT: rien a fusionner."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion TXT: telechargement"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion: +"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion: aucune nouvelle chaine (source:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusion: telechargement"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner M3U depuis URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner M3U depuis fichier"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner Streams (API)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner depuis une URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner la selection"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner liens (fichier .txt)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner playlist"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Fusionner playlist du Salon"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Groupe"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Guide EPG —"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Guide…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Heures"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Host"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "INFO"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "INSERT INTO epg_programs(tvg_id, start_ts, stop_ts, title, desc) VALUES (?,?,?,?,?)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "INSERT INTO epg_sources(name, url, enabled) VALUES (?,?,?)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "INSERT INTO playlists(name, url, epg_url) VALUES (?,?,?)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "IPTV Cleaner (PySide6)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Import URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Import local"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importer M3U (URL)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importer M3U (fichier)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importer depuis une URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importer la selection"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Importé:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Index"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Index (countries)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Index (grouped by category)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Index (grouped by language)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Indicateurs"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Info"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Info tab checks"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO (GET"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO (invalid url)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO (no url)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO (timeout)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "KO (worker exception:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "L0:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "LENGTH:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "LINE"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Language"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Langue"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Langues"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecteur"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecteur VLC chargé au premier usage."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecteur: aucune playlist chargee."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecteur: erreur chargement playlist:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecteur: playlist chargee ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lecture:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Limite le nombre de chaines affichees pour garder le guide reactif."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Lister playlists (API iptv-org)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Log"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "M3U (*.m3u *.m3u8);;Tous (*.*)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "M3U (*.m3u)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Main"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Main uniquement"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant: (EPG pas chargé)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant: (erreur EPG:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant: (pas de tvg-id)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant: -"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Maintenant: —"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Max"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Mettre à jour EPG"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Movie 24/7"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Mozilla/5.0"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Nb candidates:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Next"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Niveau"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Nom"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Nom de la playlist (Salon) :"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Nom du site (doit exister dans SITES.md, ex: \"tvhebdo.com\")"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "OK (GET"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "OK (HEAD"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "OK: playlists chargées. Déplie Category/Language/Country puis sélectionne → « Charger la sélection »."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Optionnel: tvg-id à rechercher pour deviner le site"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Options"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Options VLC:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Ouvrir dans l’éditeur"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PLAYLISTS.md"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PRAGMA foreign_keys=ON;"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PRAGMA journal_mode=WAL;"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PRAGMA table_info(channels)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PRAGMA table_info(playlists)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "PYTHONIOENCODING"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Parcourir..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Pas (min)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Pause"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Pays"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Plage (heures)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Play"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlist"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlist #"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlist existante"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlist vide"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlists (API)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Playlists index"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Previous"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Qualite"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rafraichir"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rafraichir (API)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rafraichir indicateurs"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rafraîchir"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rafraîchir guide"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Raisons"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Range"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Recherche (nom, channel, timezone, etc.)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Recherche (title, channel, url, host, quality)..."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rechercher (ex: french, canada, sports)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Rechercher (nom, url)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Remplacer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Resultats:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Risque"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Risque (indicatif, informatif uniquement):"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Récupération playlists (api iptv-org, fallback PLAYLISTS.md)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "SELECT id, name, url, COALESCE(epg_url, '') FROM playlists ORDER BY id DESC"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "SELECT id, name, url, enabled FROM epg_sources ORDER BY id DESC"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "SELECT id, name, url, enabled FROM epg_sources WHERE enabled=1 ORDER BY id DESC"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "SITES.md"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "SITES.md introuvable dans"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "STATUS:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon #"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: DB non initialisée."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: aucune playlist disponible."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: charge dans le player ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: choix invalide."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: erreur DB:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: erreur lecture playlist:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: erreur mise à jour playlist:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: erreur player:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: erreur suppression playlist:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: playlist #"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: playlist supprimée (vide)."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: playlist vide."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Salon: rien à exporter (liste vide/filtree vide)."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Source"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Source playlists: API iptv-org (feeds.json)."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Source playlists: fallback PLAYLISTS.md."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Statut"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Stop"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Stop demande."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Stream"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams (API)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams (API)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams: chargement OK ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams: erreur API:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams: fusion KO:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams: fusion OK ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Streams: import OK ->"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Style Qt"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Subdivision/City"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprime selection:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprimer"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprimer KO"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprimer la playlist #"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprimer selection"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Supprimé KO:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Sélectionne une émission pour voir la description."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "TF1"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "THEME_NAME"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Telechargement:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test URLs:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test URLs: 0/"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test URLs: stop demande"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test URLs: termine ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test deja en cours."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Test termine."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Tester URLs"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Texte"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Texte (*.txt);;Tous (*.*)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Thème"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Timezone"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Timezones"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Titre"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Tous formats"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Tous pays"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Tous timezones"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Toutes langues"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Toutes qualites"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Tâche réseau"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "UPDATE epg_sources SET enabled=? WHERE id=?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "UPDATE playlists SET name=?, url=?, epg_url=? WHERE id=?"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "URL"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "URL EPG (ex: http://localhost:3000/guide.xml ou .xml.gz)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Une playlist nommée '"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "User-Agent"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "VLC"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "VLC installé"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "VLC test"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Vol"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "WARN"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "WARNING"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Windows"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "WindowsVista"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "XMLTV (*.xml);;Tous (*.*)"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "Yes"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "[DONE] exit_code="),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "[FIND] Aucun match pour tvg-id:"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "[FIND] tvg-id trouvé dans"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "[RUN] cwd="),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "[TIMEOUT] Process tué après"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "chaînes ("),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "filtree chaînes (nom, groupe, tvg-id, url)…"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "mis à jour"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "npm absent"),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "playlists en DB."),  # i18n/strings_noop.py
    QT_TRANSLATE_NOOP('App', "yyyy-MM-dd HH:mm"),  # i18n/strings_noop.py
]
